---
title: "Analise Musicas Spotify"
author: "André Britto"
date: "23/06/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("markdown")
library(dplyr)
library(readr)
library(ggplot2)
library(treemap)
library(DT)
```

### Analise de Músicas do Spotify

## I - Cada Continente tem seu Estilo

```{r  fig.height=7, fig.width = 11, warning = FALSE}

df_features <- read_csv('dataset/SpotifyFeatures.csv',locale = locale(encoding = "UTF-8"))
```

```{r  fig.height=7, fig.width = 11, warning = FALSE, include = FALSE, echo=FALSE}

musica_genero<-df_features %>% select(track_name,genre,popularity,danceability,energy, valence)
musica_genero <-musica_genero %>% group_by(track_name) %>% top_n(1,popularity)
musica_genero <- musica_genero %>% top_n(1,genre)
colnames(musica_genero)<-c('faixa','genero','popularidade','danceability','energy','valence')
musica_genero <- musica_genero[,c('faixa','genero','popularidade','danceability','energy','valence')]
df_stream_17_18 <- read_csv('dataset/data-spotifyStreamming.csv',locale = locale(encoding = "UTF-8"))
df_stream_17_18$Region <-toupper(df_stream_17_18$Region)
colnames(df_stream_17_18) <-  c('posicao','faixa','artista','execucao','url','data_execucao','region')
df_tocadas <- df_stream_17_18 %>% filter( !is.na(artista) ) 
rm(df_stream_17_18)
tocadas_musica_genero<-inner_join(df_tocadas,musica_genero)
tocadas_musica_genero <- tocadas_musica_genero[,c("faixa","artista","data_execucao","region","genero",'popularidade','danceability','energy','valence')]
df_paises <- read_csv('dataset/iso3166.csv',locale = locale(encoding = "UTF-8"))[,c("name","alpha-2","region","sub-region")]
colnames(df_paises) <-  c('pais','sigla','continente','sub-continente')
tocadas_musica_genero_pais_continente <- inner_join(tocadas_musica_genero,df_paises, by=c("region" = "sigla"))

#rm(tocadas_musica_genero,df_paises,df_tocadas, df_tocadas_regiao, musica_genero)
```


```{r  fig.height=7, fig.width = 11, warning = FALSE}

# relatorios ###################################################
# quest01 - 1 - Qual são os 5 generos musical mais popular por continente

quest01 <-  tocadas_musica_genero_pais_continente %>% 
  group_by(continente, genero) %>% summarise(qtd = n())
resp01 <- quest01 %>% arrange(-qtd,continente) %>% top_n(5)
resp01 <- resp01 %>% group_by(genero) %>% mutate(percent=round(100*(qtd/sum(resp01$qtd)),2))

```

### Tabela de Execução de Genero por Continente

```{r  fig.height=7, fig.width = 11, warning = FALSE}
DT::datatable(resp01, class = 'cell-border stripe')
```

### Grafico de Execução por Genero
```{r  fig.height=7, fig.width = 11, warning = FALSE}
total_qtd = sum(resp01$qtd)

ggplot(data = resp01, aes(x=continente, y=genero, label= paste(round(percent,2),'%') , fill= percent)) + 
  geom_tile() +
  geom_text()+
  labs(title = "Total de Execução por Genero", x='',y='') +
  guides(fill=guide_legend(title = paste("% Sobre o \n Total de Execuções:", total_qtd )))

# Librando memoria
rm(quest01)
```

## II - Quem dita a Moda 
```{r  fig.height=7, fig.width = 11, warning = FALSE}

quest02 <-tocadas_musica_genero_pais_continente %>%
  select (genero, artista) %>% 
  filter(genero %in% resp01$genero) %>%
  group_by(genero,artista) %>%
  summarise(qtd_toca = n() ) 

resp02 <- quest02 %>%  arrange(-qtd_toca) %>% top_n(1)

```

```{r  fig.height=7, fig.width = 11, warning = FALSE}
ggplot(resp02, aes(x=resp02$qtd_toca, y=resp02$artista, color=resp02$genero)) +
  geom_point(size=3) +
  geom_text(label=resp02$qtd_toca, nudge_x = 0.25, nudge_y = 0.25, check_overlap = T) +
  geom_segment(aes(x=0 , y=resp02$artista, xend=resp02$qtd_toca , yend=resp02$artista )) + 
  labs(title = "Total de Execução de Generos em Cada Continente", x='',y='') +
  guides(color=guide_legend(title ="Genero"))

```

## III - As Top 10 dos Estilosos

```{r  fig.height=7, fig.width = 11, warning = FALSE}
artistas_10_mais <- head(resp02 %>% arrange(-qtd_toca), 10)
artistas_10_mais <- artistas_10_mais['artista'] %>% distinct() %>% unlist

resp03<-tocadas_musica_genero_pais_continente %>% 
  select(artista, faixa, genero) %>%
  filter(artista %in% artistas_10_mais) %>%
arrange(artista) %>%
  distinct() %>%
  group_by(artista) %>%
  top_n(10)
```

```{r  fig.height=7, fig.width = 11, warning = FALSE}
 DT::datatable(resp03, class = 'cell-border stripe')

```

## IV - Os Reis dos Quatro Cantos do Mundo

```{r  fig.height=7, fig.width = 11, warning = FALSE}
artis_pais_continente <-tocadas_musica_genero_pais_continente [,c('artista', 'pais', "continente")]
artis_pais_continente %>% arrange(artista)
resp_aux <-artis_pais_continente %>% group_by(artista) %>% count(continente) %>% arrange(-n)
resp_aux <- head(resp_aux,100)
resp04 <- resp_aux %>% group_by(artista,continente) %>% summarise(rnk = max(n))
resp04 <-resp04 %>% group_by(continente) %>% top_n(3)
rm(resp_aux)
```

```{r  fig.height=7, fig.width = 11, warning = FALSE}
treemap(resp04,
         # definindo os niveis hierarquicos
         index = c("continente", "artista"),
         # variavel numerica que define o tamanho dos blocos
         vSize = "rnk",
         # titulo
         title = "Os Reis dos Quatro Cantos",
         # definir estilo da fonte e ajuste vertical para cada um dos niveis hierarquicos
         fontsize.labels = c(12,10),
         align.labels = list(c("centre","centre"),c("left","top")),
         ymod.labels = c(0.6, 0, 0)
 ) 
```

## V - Tentativa de predição ...

```{r  fig.height=7, fig.width = 11, warning = FALSE}
```